name: numeroadivina
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^9.2.0
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
